import assert from 'node:assert/strict'; import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path'; import { spawn } from 'node:child_process'; import { JsonStore } from '../lib/persian-automation.mjs';
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'pendpost-lock-')); const moduleUrl = new URL('../lib/persian-automation.mjs', import.meta.url).href;
const workers = Array.from({ length: 8 }, (_, i) => new Promise((resolve, reject) => { const source = `import { JsonStore } from ${JSON.stringify(moduleUrl)}; const store = new JsonStore(${JSON.stringify(root)}); for (let n=0;n<20;n++) store.saveItem({id:${JSON.stringify(`worker-${i}`)}, n});`; const child = spawn(process.execPath, ['--input-type=module', '--eval', source]); let stderr = ''; child.stderr.on('data', (chunk) => { stderr += chunk; }); child.on('error', reject); child.on('exit', (code) => code === 0 ? resolve() : reject(new Error(stderr || `worker exited ${code}`))); })); await Promise.all(workers);
const items = new JsonStore(root).items(); assert.equal(items.length, 8); assert.deepEqual(items.map((item) => item.id).sort(), Array.from({ length: 8 }, (_, i) => `worker-${i}`)); assert.ok(items.every((item) => item.n === 19));
const staleStore = new JsonStore(root, { staleLockMs: 1 }); const lock = `${staleStore.file('content')}.lock`; fs.mkdirSync(lock); fs.writeFileSync(path.join(lock, 'owner-dead'), 'dead'); fs.utimesSync(lock, new Date(0), new Date(0)); staleStore.saveItem({ id: 'after-stale-lock' }); assert.ok(staleStore.items().some((item) => item.id === 'after-stale-lock')); assert.equal(fs.existsSync(lock), false);

const waitFor = async (file) => { const deadline = Date.now() + 5000; while (!fs.existsSync(file)) { if (Date.now() >= deadline) throw new Error(`timed out waiting for ${file}`); await new Promise((resolve) => setTimeout(resolve, 10)); } };
const runOwner = (marker, resume, staleLockMs) => { const source = `import fs from 'node:fs'; import { JsonStore } from ${JSON.stringify(moduleUrl)}; const store = new JsonStore(${JSON.stringify(root)}, {staleLockMs:${staleLockMs},lockTimeoutMs:5000}); store.withLock('ownership-race', () => { fs.writeFileSync(${JSON.stringify(marker)}, 'ready'); while (!fs.existsSync(${JSON.stringify(resume)})) Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 10); });`; const child = spawn(process.execPath, ['--input-type=module', '--eval', source]); let stderr = ''; child.stderr.on('data', (chunk) => { stderr += chunk; }); const done = new Promise((resolve, reject) => { child.on('error', reject); child.on('exit', (code) => code === 0 ? resolve() : reject(new Error(stderr || `owner exited ${code}`))); }); return { child, done }; };
const aReady = path.join(root, 'a-ready'); const aResume = path.join(root, 'a-resume'); const bReady = path.join(root, 'b-ready'); const bResume = path.join(root, 'b-resume'); const raceLock = `${new JsonStore(root).file('ownership-race')}.lock`;
const a = runOwner(aReady, aResume, 30000); await waitFor(aReady); fs.utimesSync(raceLock, new Date(0), new Date(0)); const b = runOwner(bReady, bResume, 1); await waitFor(bReady); fs.writeFileSync(aResume, 'resume'); await a.done; assert.equal(fs.existsSync(raceLock), true, 'resumed stale owner must not delete the replacement owner lock'); assert.equal(fs.readdirSync(raceLock).length, 1); fs.writeFileSync(bResume, 'resume'); await b.done; assert.equal(fs.existsSync(raceLock), false);
console.log('persian JSON store cross-process lock + stale recovery + ownership race: ok');
