import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';

const escapeXml = (value) => String(value).replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]));
const wrap = (text, length = 28) => { const words = String(text).split(/\s+/); const lines = []; let line = ''; for (const word of words) { if (`${line} ${word}`.trim().length > length) { lines.push(line); line = word; } else line = `${line} ${word}`.trim(); } if (line) lines.push(line); return lines; };
function embeddedFont(profile) { const fontPath = profile.fontPath || process.env.PERSIAN_FONT_PATH; if (!fontPath) return ''; const bytes = fs.readFileSync(fontPath); const extension = path.extname(fontPath).toLowerCase(); const mime = extension === '.woff2' ? 'font/woff2' : extension === '.woff' ? 'font/woff' : 'font/ttf'; return `@font-face{font-family:'PendpostCustom';src:url(data:${mime};base64,${bytes.toString('base64')}) format('${extension.slice(1) || 'truetype'}');}`; }
export function sceneSvg({ text, index, total, profile, portrait = false }) {
  const [background, ink, accent] = profile.brandColors; const width = 1080; const height = portrait ? 1920 : 1350; const lines = wrap(text, portrait ? 24 : 29); const family = profile.fontPath || process.env.PERSIAN_FONT_PATH ? 'PendpostCustom' : escapeXml(profile.font || 'Vazirmatn');
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}"><style>${embeddedFont(profile)}</style><rect width="100%" height="100%" fill="${index % 2 ? ink : background}"/><circle cx="920" cy="140" r="180" fill="${accent}" opacity=".18"/><rect x="72" y="90" width="12" height="160" rx="6" fill="${accent}"/><text x="930" y="${height * .39}" direction="rtl" unicode-bidi="plaintext" text-anchor="end" fill="${index % 2 ? background : ink}" font-family="${family},Vazirmatn,Tahoma,sans-serif" font-size="72" font-weight="700">${lines.map((line, lineIndex) => `<tspan x="930" dy="${lineIndex ? 105 : 0}">${escapeXml(line)}</tspan>`).join('')}</text><text x="72" y="${height - 92}" direction="ltr" fill="${accent}" font-family="Arial" font-size="34">${escapeXml(profile.instagramId)}</text><text x="930" y="${height - 92}" text-anchor="end" fill="${index % 2 ? background : ink}" opacity=".55" font-size="30">${index + 1} / ${total}</text></svg>`;
}
export async function rasterizeSvg(svg, target, { width, height, sharpFactory } = {}) { const sharp = sharpFactory || (await import('sharp')).default; await sharp(Buffer.from(svg), { density: 144 }).resize(width, height, { fit: 'fill' }).png().toFile(target); return target; }
function runCommand(binary, args) { const result = spawnSync(binary, args, { encoding: 'utf8', windowsHide: true }); if (result.status !== 0) throw new Error(`${binary} failed: ${result.stderr || result.error?.message}`); return result; }
export async function renderCarousel(item, profile, outputRoot, { rasterize = rasterizeSvg } = {}) {
  const directory = path.join(outputRoot, item.id, 'carousel'); fs.mkdirSync(directory, { recursive: true }); const selected = item.slides.slice(0, 8); const files = [];
  for (const [index, text] of selected.entries()) { const source = path.join(directory, `slide-${index + 1}.svg`); const target = path.join(directory, `slide-${index + 1}.png`); const markup = sceneSvg({ text, index, total: selected.length, profile }); fs.writeFileSync(source, markup); await rasterize(markup, target, { width: 1080, height: 1350 }); files.push(target); }
  fs.writeFileSync(path.join(directory, 'manifest.json'), `${JSON.stringify({ id: item.id, format: '1080x1350 PNG', files }, null, 2)}\n`); return files;
}
export async function renderReel(item, profile, outputRoot, { ffmpeg = process.env.FFMPEG_PATH || 'ffmpeg', narrationPath = '', rasterize = rasterizeSvg, command = runCommand } = {}) {
  const directory = path.join(outputRoot, item.id, 'reel'); fs.mkdirSync(directory, { recursive: true }); const frames = reelFrames(item); const inputs = [];
  for (const [index, text] of frames.entries()) { const source = path.join(directory, `scene-${index + 1}.svg`); const png = path.join(directory, `scene-${index + 1}.png`); const markup = sceneSvg({ text, index, total: frames.length, profile, portrait: true }); fs.writeFileSync(source, markup); await rasterize(markup, png, { width: 1080, height: 1920 }); inputs.push('-loop', '1', '-t', '5', '-i', png); }
  const video = path.join(directory, 'reel.mp4'); const concat = frames.map((_, index) => `[${index}:v]scale=1080:1920,format=yuv420p[v${index}]`).join(';') + `;${frames.map((_, index) => `[v${index}]`).join('')}concat=n=${frames.length}:v=1:a=0[v]`; const args = ['-y', ...inputs]; if (narrationPath) args.push('-i', narrationPath); args.push('-filter_complex', concat, '-map', '[v]', ...(narrationPath ? ['-map', `${frames.length}:a`, '-shortest'] : []), '-r', '30', '-c:v', 'libx264', '-pix_fmt', 'yuv420p', video); command(ffmpeg, args); return video;
}
export function reelFrames(item) { return [...item.slides]; }
export class NoopTtsProvider { async synthesize() { return null; } }
