import { accountStatus, recordMetaBlock } from './accounts.mjs';

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
const PERMANENT_CODES = new Set([10, 100, 190, 200, 368, 2207001, 2207003]);
export function assertMetaPublishingAllowed(meta = accountStatus().meta) { if (meta.paused) { const error = new Error('meta_publishing_paused'); error.code = 'lane_paused'; error.retryable = false; throw error; } if (meta.block?.tracked && meta.block.blockedUntil !== null) { const error = new Error('meta_action_blocked_368'); error.code = 368; error.retryable = false; throw error; } }
export class InstagramGraphPublisher {
  constructor({ token = process.env.META_PAGE_TOKEN || process.env.META_SYSTEM_USER_TOKEN, igUserId = process.env.META_IG_USER_ID, graphVersion = process.env.META_GRAPH_VERSION || 'v23.0', dryRun = process.env.PERSIAN_DRY_RUN !== 'false', maxAttempts = Number(process.env.META_MAX_ATTEMPTS || 3), baseBackoffMs = Number(process.env.META_RETRY_BASE_MS || 30000), fetchImpl = fetch, wait = sleep, now = () => new Date(), writeGate = assertMetaPublishingAllowed, persistItem = null } = {}) { this.token = token; this.igUserId = igUserId; this.base = `https://graph.facebook.com/${graphVersion}`; this.dryRun = dryRun; this.maxAttempts = Math.min(5, Math.max(1, maxAttempts)); this.baseBackoffMs = baseBackoffMs; this.fetch = fetchImpl; this.wait = wait; this.now = now; this.writeGate = writeGate; this.persistItem = persistItem; }
  async persist(item) { if (!this.persistItem) throw new Error('meta_persistence_required'); await this.persistItem(item); }
  async call(url, init = {}) { if (String(init.method || 'GET').toUpperCase() !== 'GET') this.writeGate(); let response; try { response = await this.fetch(url, init); } catch (cause) { const error = new Error(`Meta network failure: ${cause.message}`); error.retryable = true; error.network = true; throw error; } let body; try { body = await response.json(); } catch (cause) { const error = new Error(`Meta unreadable response: ${cause.message}`); error.retryable = true; error.network = true; throw error; } if (!response.ok || body.error) { const error = new Error(body.error?.message || `Meta HTTP ${response.status}`); error.code = body.error?.code; error.retryable = !PERMANENT_CODES.has(error.code) && (response.status === 429 || response.status >= 500 || [1, 2, 4, 17, 32, 613].includes(error.code)); if (error.code === 368) recordMetaBlock({ blockedUntil: new Date(Date.now() + 86400000).toISOString(), reason: error.message, source: 'persian-meta', actor: 'persian-meta' }); throw error; } return body; }
  validate(item) { const urls = item.publicMediaUrls || []; const image = (url) => { try { return new URL(url).protocol === 'https:' && /\.(png|jpe?g)$/i.test(new URL(url).pathname); } catch { return false; } }; const video = (url) => { try { return new URL(url).protocol === 'https:' && /\.mp4$/i.test(new URL(url).pathname); } catch { return false; } }; if (item.type === 'carousel' && (urls.length < 2 || urls.length > 10 || !urls.every(image))) throw new Error('invalid_carousel_media'); if (item.type === 'reel' && (urls.length !== 1 || !video(urls[0]))) throw new Error('invalid_reel_media'); if (!['carousel', 'reel'].includes(item.type)) throw new Error('unsupported_instagram_type'); return urls; }
  async attempt(item) {
    const urls = this.validate(item); let creationId = item.publish.containerId;
    if (!creationId && item.type === 'carousel') { const children = []; for (const imageUrl of urls) { const child = await this.call(`${this.base}/${this.igUserId}/media`, { method: 'POST', body: new URLSearchParams({ image_url: imageUrl, is_carousel_item: 'true', access_token: this.token }) }); children.push(child.id); } creationId = (await this.call(`${this.base}/${this.igUserId}/media`, { method: 'POST', body: new URLSearchParams({ media_type: 'CAROUSEL', children: children.join(','), caption: `${item.caption}\n\n${item.hashtags.join(' ')}`, access_token: this.token }) })).id; }
    if (!creationId && item.type === 'reel') creationId = (await this.call(`${this.base}/${this.igUserId}/media`, { method: 'POST', body: new URLSearchParams({ media_type: 'REELS', video_url: urls[0], caption: `${item.caption}\n\n${item.hashtags.join(' ')}`, share_to_feed: 'true', access_token: this.token }) })).id;
    item.publish.containerId = creationId; await this.persist(item);
    for (let i = 0; i < 20; i++) { const status = await this.call(`${this.base}/${creationId}?fields=status_code,status&access_token=${encodeURIComponent(this.token)}`); if (status.status_code === 'FINISHED') break; if (status.status_code === 'ERROR' || i === 19) { const error = new Error(`container_processing_failed: ${status.status || status.status_code}`); error.retryable = false; throw error; } await this.wait(3000); }
    item.publish.publishRequestedAt = this.now().toISOString(); item.publish.reconciliationRequired = true; item.status = 'publish_in_flight'; await this.persist(item);
    try { return await this.call(`${this.base}/${this.igUserId}/media_publish`, { method: 'POST', body: new URLSearchParams({ creation_id: creationId, access_token: this.token }) }); } catch (error) { if (error.network) { item.publish.ambiguous = true; item.status = 'publish_unknown'; await this.persist(item); const ambiguous = new Error('instagram_publish_result_ambiguous_manual_reconciliation_required'); ambiguous.retryable = false; ambiguous.ambiguous = true; throw ambiguous; } item.publish.reconciliationRequired = false; await this.persist(item); throw error; }
  }
  async publish(item) {
    if (item.status !== 'approved' && item.status !== 'publish_failed') throw new Error('explicit_approval_required');
    if (item.publish?.instagramPostId) return { duplicatePrevented: true, id: item.publish.instagramPostId }; if (item.publish?.ambiguous) throw new Error('ambiguous_publish_requires_manual_reconciliation');
    if (this.dryRun) return { dryRun: true, id: null }; if (!this.token || !this.igUserId) throw new Error('Meta environment is incomplete'); if (!this.persistItem) throw new Error('meta_persistence_required'); item.publish ||= { attempts: 0 };
    while ((item.publish.attempts || 0) < this.maxAttempts) { item.publish.attempts = (item.publish.attempts || 0) + 1; item.publish.lastAttemptAt = this.now().toISOString(); await this.persist(item); try { const published = await this.attempt(item); item.publish.instagramPostId = published.id; item.publish.publishedAt = this.now().toISOString(); item.publish.error = null; item.publish.nextRetryAt = null; item.publish.reconciliationRequired = false; item.status = 'published'; await this.persist(item); return { id: published.id, attempts: item.publish.attempts }; } catch (error) { item.publish.error = { message: error.message, code: error.code || null, retryable: Boolean(error.retryable), ambiguous: Boolean(error.ambiguous), at: this.now().toISOString() }; if (!error.retryable || item.publish.attempts >= this.maxAttempts) { item.status = error.ambiguous ? 'publish_unknown' : 'publish_failed'; await this.persist(item); throw error; } const delay = this.baseBackoffMs * (2 ** (item.publish.attempts - 1)); item.publish.nextRetryAt = new Date(this.now().getTime() + delay).toISOString(); item.status = 'publish_failed'; await this.persist(item); await this.wait(delay); } }
    throw new Error('meta_retry_limit_reached');
  }
}
